//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterDetailJS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projektit
    {
        public int ProjektiId { get; set; }
        public string Nimi { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
